name: Azure Static Web Apps CI/CD

on: workflow_dispatch

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-20.04
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - name: Setup GitHub Packages
        run: |
          echo "@ddradar:registry=https://npm.pkg.github.com/" > api/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> api/.npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_TREE_09D43C100 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          # see: https://aka.ms/swaworkflowconfig
          app_location: '/'
          app_build_command: yarn run:client build
          app_artifact_location: 'client/dist'
          api_location: 'api'
          api_build_command: yarn build
        env:
          API_URL: '/'
          APPINSIGHTS_INSTRUMENTATIONKEY: ${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY_PRODUCTION }}
