name: staging

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'functions/**'
      - '**.md'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'functions/**'
      - '**.md'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event.action != 'closed' && !contains(github.actor, '[bot]'))
    runs-on: ubuntu-20.04
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - name: Setup GitHub Packages
        run: |
          echo "@ddradar:registry=https://npm.pkg.github.com/" > api/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> api/.npmrc
          echo "@ddradar:registry=https://npm.pkg.github.com/" > client/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> client/.npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_WATER_096A66800 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          # see: https://aka.ms/swaworkflowconfig
          app_location: /
          app_build_command: yarn run-s "run:core {1}" "run:client {1}" -- build
          app_artifact_location: client/dist
          api_location: api
          api_build_command: yarn build
        env:
          API_URL: '/'
          APPINSIGHTS_INSTRUMENTATIONKEY: ${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY_STAGING }}
          SONGS_API_URL: 'https://api.ddradar.app/api/v1/songs'

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-20.04
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_WATER_096A66800 }}
          action: 'close'
