name: Crowdin Sync

on:
  push:
    branches:
      - main
    paths:
      - 'crowdin.yml'
      - '.github/workflows/crowdin.yml'
      - 'i18n/locales/**'
      - 'content/**'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-crowdin:
    name: Sync with Crowdin
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1 # Should be 1 to avoid parallel builds
      matrix:
        lc: [ja, ko] # Target languages https://developer.crowdin.com/language-codes/

    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v2.2.1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Crowdin Action
        uses: crowdin/github-action@v2.14.0
        with:
          upload_sources: true
          upload_translations: true
          download_translations: true
          download_language: ${{ matrix.lc }}
          commit_message: 'chore(i18n): sync translations from Crowdin (${{ matrix.lc }})'
          localization_branch_name: chore/l10n_${{ matrix.lc }}
          create_pull_request: false

      - name: Create Pull Request
        run: |
          if git ls-remote --exit-code --heads origin $PR_BRANCH; then
            if ! gh pr view $PR_BRANCH >/dev/null 2>&1; then
              gh pr create \
                --title "$PR_TITLE" \
                --body "$PR_BODY" \
                --head $PR_BRANCH \
                --base ${{ github.ref_name }} \
                --label "$PR_LABEL"
            else
              echo "Pull request already exists for $PR_BRANCH. Skipping creation."
            fi
          else
            echo "No changes found. Skipping Pull request creation."
          fi
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          PR_BRANCH: 'chore/l10n_${{ matrix.lc }}'
          PR_TITLE: 'chore(i18n): sync translations from Crowdin (${{ matrix.lc }})'
          PR_BODY: |
            This PR updates translation files from Crowdin.

            Please review the changes before merging.
          PR_LABEL: 'documentation :memo:, i18n :globe_with_meridians:'
