name: Crowdin Sync

on:
  push:
    branches:
      - main
    paths:
      - 'crowdin.yml'
      - '.github/workflows/crowdin.yml'
      - 'i18n/locales/**'
      - 'content/**'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync-crowdin:
    name: Sync with Crowdin
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1 # Should be 1 to avoid parallel builds
      matrix:
        lc: [ja, ko] # Target languages https://developer.crowdin.com/language-codes/

    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v2.2.1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Cache Crowdin source files
        uses: actions/cache@v5.0.3
        with:
          path: ~/.crowdin/cache.json
          key: ${{ runner.os }}-crowdin-cache-${{ github.ref_name }}-${{ hashFiles('**/crowdin.yml') }}
          restore-keys: |
            ${{ runner.os }}-crowdin-cache-${{ github.ref_name }}-

      - name: Crowdin Action
        uses: crowdin/github-action@v2.14.0
        with:
          upload_sources: true
          upload_translations: true
          upload_sources_args: '--cache'
          download_translations: true
          download_language: ${{ matrix.lc }}
          commit_message: 'chore(i18n): sync translations from Crowdin (${{ matrix.lc }})'
          localization_branch_name: 'chore/${{ github.ref_name }}/l10n_${{ matrix.lc }}'
          create_pull_request: true
          pull_request_title: 'chore(i18n): sync translations from Crowdin (${{ matrix.lc }})'
          pull_request_body: |
            This PR updates translation files from Crowdin.

            Please review the changes before merging.
          pull_request_labels: 'documentation :memo:,i18n :globe_with_meridians:'
          pull_request_base_branch_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
